version: "3"

services:

  purpev-api:
    build:
      context: ../services/api/
      dockerfile: Dockerfile.prod
    ports:
      - 1240:1240

  purpev-web:
    build:
      context: ../services/web/
      dockerfile: Dockerfile.prod
    ports:
      - 1239:1239

  purpev-postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - purpev_postgres_volume:/var/lib/postgresql/data

volumes:
  purpev_postgres_volume:
    external: true